[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "trask"
version = "0.1.0"
dependencies = ["click", "tabulate"]

[project.scripts]
trask = "trask.main:main"

